version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: tododb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo-net

  api:
    build: ./api
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:example@db:5432/tododb"
    ports:
      - "8000:8000"
    networks:
      - todo-net

  frontend:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "8080:8080"
    networks:
      - todo-net

  checker:
    build: ./checker
    environment:
      - DATABASE_URL=postgresql://postgres:example@db:5432/tododb
    ports:
      - "8001:8000"
    networks:
      - todo-net

volumes:
  pgdata:

networks:
  todo-net:
    driver: bridge
