# advisor-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: advisor
  namespace: password-advisor
spec:
  selector:
    app: advisor
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
