apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: password-advisor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shah10d/frontend:v2.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /checker.html
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
