# Exposes the Frontend static web server internally via a ClusterIP Service.
# Allows the Ingress controller to route external HTTP traffic to the frontend pod
# using the DNS name 'frontend' within the 'password-advisor' namespace.
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: password-advisor
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
